{
 "title": "Enterprise OTel Stack - Overview",
 "tags": [
  "fastapi",
  "otel"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Simulated Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "active_simulated_users" }
   ]
  },
  {
   "title": "Total Request Rate (All endpoints)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_count_total[$__rate_interval]))",
     "legendFormat": "Requests / sec"
    }
   ]
  },
  {
   "title": "Application Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{service_name=\"fastapi-otel-demo\"}"
    }
   ]
  }
 ]
}